name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install kind CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: kubernetes-sigs/kind
          extension-matching: disable
          rename-to: kind
          chmod: 0755
      - name: Install k3d CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: k3d-io/k3d
          extension-matching: disable
          rename-to: k3d
          chmod: 0755
      - name: Install talosctl CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: siderolabs/talos
          extension-matching: disable
          asset-name: talosctl
          rename-to: talosctl
          chmod: 0755
      - name: Install flux CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: fluxcd/flux2
      - name: Install ArgoCD CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: argoproj/argo-cd
          extension-matching: disable
          rename-to: argocd
          chmod: 0755
      - uses: azure/setup-kubectl@v4
      - uses: azure/setup-helm@v4.3.0
      - name: Install Cilium CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: cilium/cilium-cli
      - name: Test .NET solution or project
        uses: devantler-tech/github-actions/composite-actions/dotnet-test-action@b8298f5d8bb6d8b1d807c22ec9847889b1471858 # v1.5.2
        with:
          app_id: ${{ vars.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
