name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install kind CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: kubernetes-sigs/kind
          extension-matching: disable
          rename-to: kind
          chmod: 0755
      - name: Install k3d CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: k3d-io/k3d
          extension-matching: disable
          rename-to: k3d
          chmod: 0755
      - name: Install talosctl CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: siderolabs/talos
          extension-matching: disable
          asset-name: talosctl
          rename-to: talosctl
          chmod: 0755
      - name: Install flux CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: fluxcd/flux2
      - name: Install ArgoCD CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: argoproj/argo-cd
          extension-matching: disable
          rename-to: argocd
          chmod: 0755
      - uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede # v4.0.1
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - name: Install Cilium CLI
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: cilium/cilium-cli
      - name: Test .NET solution or project
        uses: devantler-tech/composite-actions/dotnet-test-action@d4b23f9e20423712a3300a63bdbaf4ac70fee721 # v.1.9.2
        with:
          app_id: ${{ vars.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
